### ISSUE TITLE
Tests failing on local (Travis, non-SauceLabs) iOS 10 device

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-wkwebview-engine#101]
https://travis-ci.org/apache/cordova-plugin-wkwebview-engine/jobs/547260689

```
** BUILD SUCCEEDED **
Deploying to simulator
Running command: /private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-2870cc3iyqjtQ38y/node_modules/ios-sim/bin/ios-sim launch /private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-2870cc3iyqjtQ38y/platforms/ios/build/emulator/HelloCordova.app --devicetypeid com.apple.CoreSimulator.SimDeviceType.iPhone-XR, 12.2 --log /private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-2870cc3iyqjtQ38y/platforms/ios/cordova/console.log --exit
[ios-sim] io.cordova.hellocordova: 3226
[ios-sim] logPath: /private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-2870cc3iyqjtQ38y/platforms/ios/cordova/console.log
Simulator successfully started via `ios-sim`.
Error: waitForConnection: Seems like device not connected to local server in 540 secs
Error: waitForConnection: Seems like device not connected to local server in 540 secs
    at Timeout.setTimeout (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:429:28)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From previous event:
    at ParamedicRunner.waitForConnection (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:426:18)
    at Q.promise (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:246:38)
    at Q.all.Q.then (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:244:38)
From previous event:
    at Q.then.then.then (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:234:25)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
From previous event:
    at ParamedicRunner.runLocalTests (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:257:14)
    at ParamedicRunner.runTests (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:345:25)
    at Q.then.then.then (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:89:29)
From previous event:
    at ParamedicRunner.run (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:75:14)
    at Object.exports.run (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:477:19)
    at Object.<anonymous> (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/main.js:184:15)
```

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
