### ISSUE TITLE
Tests failing on iOS 12.2

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-wkwebview-engine#102]
https://travis-ci.org/apache/cordova-plugin-wkwebview-engine/jobs/547260692

```
cordova-paramedic: Tests failed to complete; ending appium session. The error is:
Error: [context("WEBVIEW_4435.2")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Remote debugger error with code '-32601': 'Page' domain was not found
    at exports.newError (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/wd/lib/utils.js:152:13)
    at /Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/wd/lib/callbacks.js:36:19
    at /Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/wd/lib/webdriver.js:194:5
    at Request._callback (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/wd/lib/http-utils.js:89:7)
    at Request.self.callback (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
From previous event:
    at ParamedicSauceLabs.runSauceTests (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/ParamedicSauceLabs.js:459:14)
    at ParamedicRunner.runTests (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:337:58)
    at Q.then.then.then (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:89:29)
```

Unclear what is happening.

**Comment by janpio** [comment]
Fixed now via update of paramedic.
